<#
.SYNOPSIS
    Regenerate the module/function map in docs/architecture.md from the real
    modules, so the map cannot drift. PowerShell counterpart of the kit's
    Python gen_arch_map.py (which only parses Python).

.DESCRIPTION
    Parses Modules/*.psm1 with the PowerShell AST, lists each module's functions
    and whether they are exported (Export-ModuleMember), and surfaces any
    'Implements: SR-/LLR-' back-link comment found in the function body. Rewrites
    the region between the BEGIN/END GENERATED MODULE MAP markers in
    docs/architecture.md.

.PARAMETER Check
    Do not write; exit 1 if the generated map differs from what's on disk
    (so CI / check.ps1 can fail when the doc is stale).

.NOTES
    Implements: (tooling — supports the traceability harness, not an SR/LLR.)
#>
[CmdletBinding()]
param([switch]$Check)

$ErrorActionPreference = 'Stop'
$repo    = [System.IO.Path]::GetDirectoryName($PSScriptRoot)
$archDoc = Join-Path $repo 'docs\architecture.md'
$modules = Get-ChildItem -LiteralPath (Join-Path $repo 'Modules') -Filter '*.psm1' | Sort-Object Name

function Get-ExportedNames {
    param([string]$Path)
    $names = [System.Collections.Generic.HashSet[string]]::new()
    $tokens = $errs = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($Path, [ref]$tokens, [ref]$errs)
    $calls = $ast.FindAll({ param($n)
        $n -is [System.Management.Automation.Language.CommandAst] -and
        $n.GetCommandName() -eq 'Export-ModuleMember' }, $true)
    foreach ($c in $calls) {
        # Collect every nested string constant (handles both bareword lists and
        # `-Function @( 'A', 'B' )` array literals), minus the command name and
        # the parameter name itself.
        $strings = $c.FindAll({ param($n)
            $n -is [System.Management.Automation.Language.StringConstantExpressionAst] }, $true)
        foreach ($s in $strings) {
            if ($s.Value -in 'Export-ModuleMember','Function','Alias','Cmdlet','Variable') { continue }
            [void]$names.Add($s.Value)
        }
    }
    return $names
}

function Get-FunctionInfo {
    param([string]$Path)
    $tokens = $errs = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($Path, [ref]$tokens, [ref]$errs)
    $exported = Get-ExportedNames -Path $Path
    $fns = $ast.FindAll({ param($n)
        $n -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $false)
    foreach ($fn in $fns) {
        $impl = ''
        $m = [regex]::Match($fn.Extent.Text, 'Implements:\s*([^\r\n#]+)')
        if ($m.Success) { $impl = $m.Groups[1].Value.Trim().TrimEnd('.') }
        [pscustomobject]@{
            Name     = $fn.Name
            Exported = ($exported.Count -eq 0) -or $exported.Contains($fn.Name)
            Implements = $impl
        }
    }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('<!-- BEGIN GENERATED MODULE MAP -->')
[void]$sb.AppendLine("_Generated by ``scripts/gen_arch_map.ps1`` from the modules' AST. Do not edit by hand;")
[void]$sb.AppendLine('run the generator. Back-links come from `Implements:` comments in each function._')
foreach ($mod in $modules) {
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("### ``Modules/$($mod.Name)``")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('| Function | Exported | Implements |')
    [void]$sb.AppendLine('|---|:---:|---|')
    foreach ($f in Get-FunctionInfo -Path $mod.FullName | Sort-Object Name) {
        $exp = if ($f.Exported) { 'yes' } else { 'no' }
        $imp = if ($f.Implements) { $f.Implements } else { '—' }
        [void]$sb.AppendLine("| ``$($f.Name)`` | $exp | $imp |")
    }
}
[void]$sb.Append('<!-- END GENERATED MODULE MAP -->')
$generated = $sb.ToString() -replace "`r`n", "`n"

$doc = (Get-Content -LiteralPath $archDoc -Raw) -replace "`r`n", "`n"
$pattern = '(?s)<!-- BEGIN GENERATED MODULE MAP -->.*?<!-- END GENERATED MODULE MAP -->'
if ($doc -notmatch $pattern) { throw "Markers not found in $archDoc" }
$updated = [regex]::Replace($doc, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $generated })

if ($Check) {
    if ($updated -ne $doc) {
        Write-Error "architecture.md module map is stale. Run: pwsh -File scripts/gen_arch_map.ps1"
        exit 1
    }
    Write-Host "[OK]  architecture.md module map is current."
    exit 0
}

Set-Content -LiteralPath $archDoc -Value $updated -NoNewline -Encoding utf8
Write-Host "Updated module map in $archDoc"
